<?php

class DBConfig {
    
    
    //define tbl_state
    CONST TABLE_STATES = ' tbl_states';
    CONST TABLE_STATES_ATT_STATE_ID = 'stateId';
    CONST TABLE_STATES_ATT_STATE_NAME = 'stateName';
    CONST TABLE_STATES_ATT_STATE_SHORT_NAME = 'stateShortName';
    CONST TABLE_STATES_ATT_COUNTRY_ID = 'countryId';

    //define tbl_city
    CONST TABLE_CITY = 'tbl_city';
    CONST TABLE_CITY_ATT_CITY_ID = 'cityId';
    CONST TABLE_CITY_ATT_CITY_NAME = 'cityName';
    CONST TABLE_CITY_ATT_STATE_ID = 'stateId';

    //define tbl_user
    CONST TABLE_USER = 'tbl_user';
    CONST TABLE_USER_ATT_USER_ID = 'userId';
    CONST TABLE_USER_ATT_USER_PASSWORD = 'userPassword';
    CONST TABLE_USER_ATT_USER_EMAIL_ADDRESS = 'userEmailAddress';
    CONST TABLE_USER_ATT_USER_LAST_LOGIN = 'lastLogin';
    CONST TABLE_USER_ATT_USER_REGISTRATION_DATE = 'registrationDate';
    CONST TABLE_USER_ATT_USER_REGISTRATION_TOKEN = 'token';
    CONST TABLE_USER_ATT_USER_STATUS = 'status';
    
    //define tbl_user_info
    CONST TABLE_USER_INFO = 'tbl_user_info';
    CONST TABLE_USER_INFO_ATT_ID = 'id';
    CONST TABLE_USER_INFO_ATT_USER_ID = 'userId';
    CONST TABLE_USER_INFO_ATT_USER_FIRST_NAME = 'userFirstName';
    CONST TABLE_USER_INFO_ATT_USER_LAST_NAME = 'userLastName';
    CONST TABLE_USER_INFO_ATT_USER_PROFILE_PIC = 'userProfilePic';
    CONST TABLE_USER_INFO_ATT_USER_DOB = 'userDOB';
    CONST TABLE_USER_INFO_ATT_USER_ZIP_CODE = 'userZipCode';
    CONST TABLE_USER_INFO_ATT_USER_STATE_ID = 'userStateId';
    CONST TABLE_USER_INFO_ATT_USER_CITY_ID = 'userCityId';
    CONST TABLE_USER_INFO_ATT_USER_ADDRESS = 'userAddress';
    CONST TABLE_USER_INFO_ATT_USER_PHONE = 'userPhone';
    
    CONST TABLE_ADMIN = 'tbl_admin';
    CONST TABLE_ADMIN_ATT_ADMIN_ID = 'adminId';
    CONST TABLE_ADMIN_ATT_ADMIN_USERNAME = 'adminUsername';
    CONST TABLE_ADMIN_ATT_ADMIN_PASSWORD = 'adminPassword';
    CONST TABLE_ADMIN_ATT_ADMIN_LAST_LOGIN_TIME = 'adminLastLoginTime';
    CONST TABLE_ADMIN_ATT_ADMIN_IS_ACTIVE = 'adminIsActive';
    CONST TABLE_ADMIN_ATT_ADMIN_PREVILEDGE = 'adminPreviledge';
    
    CONST TABLE_CONTENT = 'tbl_content';
    CONST TABLE_CONTENT_ATT_CONTENT_ID = 'contentId';
    CONST TABLE_CONTENT_ATT_CONTENT_NAME = 'contentName';
    CONST TABLE_CONTENT_ATT_CONTENT_TITLE = 'contentTitle';
    CONST TABLE_CONTENT_ATT_CONTENT_DETAILS = 'contentDetails';
    
    CONST TABLE_FAQ = 'tbl_faq';
    CONST TABLE_FAQ_ATT_FAQ_ID = 'faqId';
    CONST TABLE_FAQ_ATT_FAQ_QUESTION = 'faqQuestion';
    CONST TABLE_FAQ_ATT_FAQ_ANSWER = 'faqAnswer';
    CONST TABLE_FAQ_ATT_ADDED_TIME = 'addedTime';
    
    
    
    CONST TABLE_SETTINGS = 'tbl_settings';
    CONST TABLE_SETTINGS_ATT_ID = 'id';
    CONST TABLE_SETTINGS_ATT_SITE_TITLE = 'siteTitle';
    CONST TABLE_SETTINGS_ATT_SITE_META_KEYWORD = 'siteMetaKeyword';
    CONST TABLE_SETTINGS_ATT_SITE_META_DESCRIPTION = 'siteMetaDescription';
    CONST TABLE_SETTINGS_ATT_SITE_LOGO = 'siteLogo';
    CONST TABLE_SETTINGS_ATT_SITE_EMAIL = 'siteEmail';
    CONST TABLE_SETTINGS_ATT_SITE_PHONE = 'sitePhone';
    CONST TABLE_SETTINGS_ATT_SITE_VENDOR_LOGO = 'siteVendorLogo';
    CONST TABLE_SETTINGS_ATT_HIDE_HOME_CONTENT = 'hideHomeContent';
    
    CONST TABLE_LIST = 'tbl_list';
    CONST TABLE_LIST_ATT_LIST_ID = 'listId';
    CONST TABLE_LIST_ATT_LIST_USER_ID = 'userId';
    CONST TABLE_LIST_ATT_LIST_NAME = 'listName';
    CONST TABLE_LIST_ATT_LIST_ADDED_DATE = 'listAddeddate';
    CONST TABLE_LIST_ATT_LIST_STATUS = 'listStatus';
    CONST TABLE_LIST_ATT_LIST_IMAGE = 'listImage';
    
    CONST TABLE_BUSINESS_CATEGORY = 'tbl_business_category';
    CONST TABLE_BUSINESS_CATEGORY_ATT_CATEGORY_ID = 'categoryId';
    CONST TABLE_BUSINESS_CATEGORY_ATT_CATEGORY_NAME = 'categoryName';
    CONST TABLE_BUSINESS_CATEGORY_ATT_CATEGORY_IMAGE = 'categoryImage';
    CONST TABLE_BUSINESS_CATEGORY_ATT_CATEGORY_ADDED_DATE = 'addedDate';
    CONST TABLE_BUSINESS_CATEGORY_ATT_CATEGORY_STATUS = 'status';
    
    CONST TABLE_BUSINESS_SUB_CATEGORY = 'tbl_business_subcategory';
    CONST TABLE_BUSINESS_SUB_CATEGORY_ATT_SUB_CATEGORY_ID = 'subcategoryId';
    CONST TABLE_BUSINESS_SUB_CATEGORY_ATT_CATEGORY_ID = 'categoryId';
    CONST TABLE_BUSINESS_SUB_CATEGORY_ATT_SUB_CATEGORY_NAME = 'subcategoryName';
    CONST TABLE_BUSINESS_SUB_CATEGORY_ATT_SUB_CATEGORY_IMAGE = 'subcategoryImage';
    CONST TABLE_BUSINESS_SUB_CATEGORY_ATT_SUB_CATEGORY_ADDED_DATE = 'addedDate';
    CONST TABLE_BUSINESS_SUB_CATEGORY_ATT_SUB_CATEGORY_STATUS = 'status';
    
    CONST TABLE_BUSINESS = 'tbl_business';
    CONST TABLE_BUSINESS_ATT_BUSINESS_ID = 'businessId';
    CONST TABLE_BUSINESS_ATT_LIST_ID = 'listId';
    CONST TABLE_BUSINESS_ATT_USER_ID = 'userId';
    CONST TABLE_BUSINESS_ATT_BUSINESS_TITLE = 'businessTitle';
    CONST TABLE_BUSINESS_ATT_BUSINESS_CATEGORY_ID = 'businessCategoryId';
    CONST TABLE_BUSINESS_ATT_BUSINESS_SUB_CATEGORY_ID = 'businessSubCategoryId';
    CONST TABLE_BUSINESS_ATT_BUSINESS_DETAILS = 'businessDetails';
    CONST TABLE_BUSINESS_ATT_BUSINESS_WEBSITE_URL = 'businessWebsiteUrl';
    CONST TABLE_BUSINESS_ATT_BUSINESS_ABOUT = 'businessAbout';
    CONST TABLE_BUSINESS_ATT_BUSINESS_RESERVATION_STATUS = 'businessReservationStatus';
    CONST TABLE_BUSINESS_ATT_BUSINESS_MENU_STATUS = 'businessMenuStatus';
    CONST TABLE_BUSINESS_ATT_BUSINESS_STATE_ID = 'businessStateId';
    CONST TABLE_BUSINESS_ATT_BUSINESS_CITY_ID = 'businessCityId';
    CONST TABLE_BUSINESS_ATT_BUSINESS_ADDED_DATE = 'addedDate';
    
    CONST TABLE_BUSINESS_ATTRIBUTE = 'tbl_business_attribute';
    CONST TABLE_BUSINESS_ATTRIBUTE_ATT_BUSINESS_ID = 'businessId';
    CONST TABLE_BUSINESS_ATTRIBUTE_ATT_BUSINESS_ATTRIBUTE_TITLE = 'businessAttrTitle';
    CONST TABLE_BUSINESS_ATTRIBUTE_ATT_BUSINESS_ATTRIBUTE_VALUE = 'businessAttrValue';
    
    CONST TABLE_BUSINESS_IMAGES = 'tbl_business_images';
    CONST TABLE_BUSINESS_IMAGES_ATT_BUSINESS_ID = 'businessId';
    CONST TABLE_BUSINESS_IMAGES_ATT_USER_ID = 'userId';
    CONST TABLE_BUSINESS_IMAGES_ATT_IMAGE_NAME = 'imageName';
    
    CONST TABLE_BUSINESS_MENU = 'tbl_business_menu';
    CONST TABLE_BUSINESS_MENU_ATT_MENU_ID = 'menuId';
    CONST TABLE_BUSINESS_MENU_ATT_BUSINESS_ID = 'businessId';
    CONST TABLE_BUSINESS_MENU_ATT_MENU_TITLE = 'menuTitle';
    CONST TABLE_BUSINESS_MENU_ATT_MENU_DETAILS = 'menuDetails';
    CONST TABLE_BUSINESS_MENU_ATT_MENU_PRICE = 'menuPrice';
    
    
}
